// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.21.12
// source: protobuf/assync_response.proto

package assync

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QueueTriggerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueueTriggerResponse) Reset() {
	*x = QueueTriggerResponse{}
	mi := &file_protobuf_assync_response_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueTriggerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueTriggerResponse) ProtoMessage() {}

func (x *QueueTriggerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_assync_response_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueTriggerResponse.ProtoReflect.Descriptor instead.
func (*QueueTriggerResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_assync_response_proto_rawDescGZIP(), []int{0}
}

func (x *QueueTriggerResponse) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

type SnsTriggerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnsTriggerResponse) Reset() {
	*x = SnsTriggerResponse{}
	mi := &file_protobuf_assync_response_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnsTriggerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnsTriggerResponse) ProtoMessage() {}

func (x *SnsTriggerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_assync_response_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnsTriggerResponse.ProtoReflect.Descriptor instead.
func (*SnsTriggerResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_assync_response_proto_rawDescGZIP(), []int{1}
}

func (x *SnsTriggerResponse) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

var File_protobuf_assync_response_proto protoreflect.FileDescriptor

const file_protobuf_assync_response_proto_rawDesc = "" +
	"\n" +
	"\x1eprotobuf/assync_response.proto\x12\x11tecmise.responses\x1a google/protobuf/descriptor.proto\"5\n" +
	"\x14QueueTriggerResponse\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\"3\n" +
	"\x12SnsTriggerResponse\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageIdBe\n" +
	")com.tecmise.connector.ports.output.assyncZ8github.com/tecmise/connector-lib/pkg/ports/output/assyncb\x06proto3"

var (
	file_protobuf_assync_response_proto_rawDescOnce sync.Once
	file_protobuf_assync_response_proto_rawDescData []byte
)

func file_protobuf_assync_response_proto_rawDescGZIP() []byte {
	file_protobuf_assync_response_proto_rawDescOnce.Do(func() {
		file_protobuf_assync_response_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protobuf_assync_response_proto_rawDesc), len(file_protobuf_assync_response_proto_rawDesc)))
	})
	return file_protobuf_assync_response_proto_rawDescData
}

var file_protobuf_assync_response_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protobuf_assync_response_proto_goTypes = []any{
	(*QueueTriggerResponse)(nil), // 0: tecmise.responses.QueueTriggerResponse
	(*SnsTriggerResponse)(nil),   // 1: tecmise.responses.SnsTriggerResponse
}
var file_protobuf_assync_response_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protobuf_assync_response_proto_init() }
func file_protobuf_assync_response_proto_init() {
	if File_protobuf_assync_response_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protobuf_assync_response_proto_rawDesc), len(file_protobuf_assync_response_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protobuf_assync_response_proto_goTypes,
		DependencyIndexes: file_protobuf_assync_response_proto_depIdxs,
		MessageInfos:      file_protobuf_assync_response_proto_msgTypes,
	}.Build()
	File_protobuf_assync_response_proto = out.File
	file_protobuf_assync_response_proto_goTypes = nil
	file_protobuf_assync_response_proto_depIdxs = nil
}
