// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.21.12
// source: protobuf/fifo_options.proto

package assync

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var file_protobuf_fifo_options_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         50007,
		Name:          "tecmise.fifo_options.deduplication_id",
		Tag:           "varint,50007,opt,name=deduplication_id",
		Filename:      "protobuf/fifo_options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         50008,
		Name:          "tecmise.fifo_options.group_id",
		Tag:           "varint,50008,opt,name=group_id",
		Filename:      "protobuf/fifo_options.proto",
	},
}

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional bool deduplication_id = 50007;
	E_DeduplicationId = &file_protobuf_fifo_options_proto_extTypes[0]
	// optional bool group_id = 50008;
	E_GroupId = &file_protobuf_fifo_options_proto_extTypes[1]
)

var File_protobuf_fifo_options_proto protoreflect.FileDescriptor

const file_protobuf_fifo_options_proto_rawDesc = "" +
	"\n" +
	"\x1bprotobuf/fifo_options.proto\x12\x14tecmise.fifo_options\x1a google/protobuf/descriptor.proto:M\n" +
	"\x10deduplication_id\x12\x1d.google.protobuf.FieldOptions\x18׆\x03 \x01(\bR\x0fdeduplicationId\x88\x01\x01:=\n" +
	"\bgroup_id\x12\x1d.google.protobuf.FieldOptions\x18؆\x03 \x01(\bR\agroupId\x88\x01\x01Bl\n" +
	"0com.tecmise.connector.ports.output.shared_kernelZ8github.com/tecmise/connector-lib/pkg/ports/output/assyncb\x06proto3"

var file_protobuf_fifo_options_proto_goTypes = []any{
	(*descriptorpb.FieldOptions)(nil), // 0: google.protobuf.FieldOptions
}
var file_protobuf_fifo_options_proto_depIdxs = []int32{
	0, // 0: tecmise.fifo_options.deduplication_id:extendee -> google.protobuf.FieldOptions
	0, // 1: tecmise.fifo_options.group_id:extendee -> google.protobuf.FieldOptions
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	0, // [0:2] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protobuf_fifo_options_proto_init() }
func file_protobuf_fifo_options_proto_init() {
	if File_protobuf_fifo_options_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protobuf_fifo_options_proto_rawDesc), len(file_protobuf_fifo_options_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 2,
			NumServices:   0,
		},
		GoTypes:           file_protobuf_fifo_options_proto_goTypes,
		DependencyIndexes: file_protobuf_fifo_options_proto_depIdxs,
		ExtensionInfos:    file_protobuf_fifo_options_proto_extTypes,
	}.Build()
	File_protobuf_fifo_options_proto = out.File
	file_protobuf_fifo_options_proto_goTypes = nil
	file_protobuf_fifo_options_proto_depIdxs = nil
}
