// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.21.12
// source: protobuf/field_options.proto

package field

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var file_protobuf_field_options_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50001,
		Name:          "tecmise.json_properties.json_name",
		Tag:           "bytes,50001,opt,name=json_name",
		Filename:      "protobuf/field_options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         50002,
		Name:          "tecmise.json_properties.omitempty",
		Tag:           "varint,50002,opt,name=omitempty",
		Filename:      "protobuf/field_options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: ([]string)(nil),
		Field:         50003,
		Name:          "tecmise.json_properties.validate",
		Tag:           "bytes,50003,rep,name=validate",
		Filename:      "protobuf/field_options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50004,
		Name:          "tecmise.json_properties.description",
		Tag:           "bytes,50004,opt,name=description",
		Filename:      "protobuf/field_options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50005,
		Name:          "tecmise.json_properties.path_variable",
		Tag:           "bytes,50005,opt,name=path_variable",
		Filename:      "protobuf/field_options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50006,
		Name:          "tecmise.json_properties.query_parameter",
		Tag:           "bytes,50006,opt,name=query_parameter",
		Filename:      "protobuf/field_options.proto",
	},
}

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional string json_name = 50001;
	E_JsonName = &file_protobuf_field_options_proto_extTypes[0]
	// optional bool omitempty = 50002;
	E_Omitempty = &file_protobuf_field_options_proto_extTypes[1]
	// repeated string validate = 50003;
	E_Validate = &file_protobuf_field_options_proto_extTypes[2]
	// optional string description = 50004;
	E_Description = &file_protobuf_field_options_proto_extTypes[3]
	// optional string path_variable = 50005;
	E_PathVariable = &file_protobuf_field_options_proto_extTypes[4]
	// optional string query_parameter = 50006;
	E_QueryParameter = &file_protobuf_field_options_proto_extTypes[5]
)

var File_protobuf_field_options_proto protoreflect.FileDescriptor

const file_protobuf_field_options_proto_rawDesc = "" +
	"\n" +
	"\x1cprotobuf/field_options.proto\x12\x17tecmise.json_properties\x1a google/protobuf/descriptor.proto:?\n" +
	"\tjson_name\x12\x1d.google.protobuf.FieldOptions\x18ц\x03 \x01(\tR\bjsonName\x88\x01\x01:=\n" +
	"\tomitempty\x12\x1d.google.protobuf.FieldOptions\x18҆\x03 \x01(\bR\tomitempty:;\n" +
	"\bvalidate\x12\x1d.google.protobuf.FieldOptions\x18ӆ\x03 \x03(\tR\bvalidate:D\n" +
	"\vdescription\x12\x1d.google.protobuf.FieldOptions\x18Ԇ\x03 \x01(\tR\vdescription\x88\x01\x01:G\n" +
	"\rpath_variable\x12\x1d.google.protobuf.FieldOptions\x18Ն\x03 \x01(\tR\fpathVariable\x88\x01\x01:K\n" +
	"\x0fquery_parameter\x12\x1d.google.protobuf.FieldOptions\x18ֆ\x03 \x01(\tR\x0equeryParameter\x88\x01\x01Bc\n" +
	"(com.tecmise.connector.ports.output.fieldZ7github.com/tecmise/connector-lib/pkg/ports/output/fieldb\x06proto3"

var file_protobuf_field_options_proto_goTypes = []any{
	(*descriptorpb.FieldOptions)(nil), // 0: google.protobuf.FieldOptions
}
var file_protobuf_field_options_proto_depIdxs = []int32{
	0, // 0: tecmise.json_properties.json_name:extendee -> google.protobuf.FieldOptions
	0, // 1: tecmise.json_properties.omitempty:extendee -> google.protobuf.FieldOptions
	0, // 2: tecmise.json_properties.validate:extendee -> google.protobuf.FieldOptions
	0, // 3: tecmise.json_properties.description:extendee -> google.protobuf.FieldOptions
	0, // 4: tecmise.json_properties.path_variable:extendee -> google.protobuf.FieldOptions
	0, // 5: tecmise.json_properties.query_parameter:extendee -> google.protobuf.FieldOptions
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	0, // [0:6] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protobuf_field_options_proto_init() }
func file_protobuf_field_options_proto_init() {
	if File_protobuf_field_options_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protobuf_field_options_proto_rawDesc), len(file_protobuf_field_options_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 6,
			NumServices:   0,
		},
		GoTypes:           file_protobuf_field_options_proto_goTypes,
		DependencyIndexes: file_protobuf_field_options_proto_depIdxs,
		ExtensionInfos:    file_protobuf_field_options_proto_extTypes,
	}.Build()
	File_protobuf_field_options_proto = out.File
	file_protobuf_field_options_proto_goTypes = nil
	file_protobuf_field_options_proto_depIdxs = nil
}
