// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.21.12
// source: protobuf/service_options.proto

package service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IntegrationKind int32

const (
	IntegrationKind_LAMBDA IntegrationKind = 0
	IntegrationKind_REST   IntegrationKind = 1
	IntegrationKind_SQS    IntegrationKind = 2
	IntegrationKind_SNS    IntegrationKind = 3
)

// Enum value maps for IntegrationKind.
var (
	IntegrationKind_name = map[int32]string{
		0: "LAMBDA",
		1: "REST",
		2: "SQS",
		3: "SNS",
	}
	IntegrationKind_value = map[string]int32{
		"LAMBDA": 0,
		"REST":   1,
		"SQS":    2,
		"SNS":    3,
	}
)

func (x IntegrationKind) Enum() *IntegrationKind {
	p := new(IntegrationKind)
	*p = x
	return p
}

func (x IntegrationKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IntegrationKind) Descriptor() protoreflect.EnumDescriptor {
	return file_protobuf_service_options_proto_enumTypes[0].Descriptor()
}

func (IntegrationKind) Type() protoreflect.EnumType {
	return &file_protobuf_service_options_proto_enumTypes[0]
}

func (x IntegrationKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IntegrationKind.Descriptor instead.
func (IntegrationKind) EnumDescriptor() ([]byte, []int) {
	return file_protobuf_service_options_proto_rawDescGZIP(), []int{0}
}

type Integration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          IntegrationKind        `protobuf:"varint,1,opt,name=kind,proto3,enum=tecmise.protocols.IntegrationKind" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Integration) Reset() {
	*x = Integration{}
	mi := &file_protobuf_service_options_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Integration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Integration) ProtoMessage() {}

func (x *Integration) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_service_options_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Integration.ProtoReflect.Descriptor instead.
func (*Integration) Descriptor() ([]byte, []int) {
	return file_protobuf_service_options_proto_rawDescGZIP(), []int{0}
}

func (x *Integration) GetKind() IntegrationKind {
	if x != nil {
		return x.Kind
	}
	return IntegrationKind_LAMBDA
}

var file_protobuf_service_options_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.ServiceOptions)(nil),
		ExtensionType: (*Integration)(nil),
		Field:         30001,
		Name:          "tecmise.protocols.integration",
		Tag:           "bytes,30001,opt,name=integration",
		Filename:      "protobuf/service_options.proto",
	},
}

// Extension fields to descriptorpb.ServiceOptions.
var (
	// optional tecmise.protocols.Integration integration = 30001;
	E_Integration = &file_protobuf_service_options_proto_extTypes[0]
)

var File_protobuf_service_options_proto protoreflect.FileDescriptor

const file_protobuf_service_options_proto_rawDesc = "" +
	"\n" +
	"\x1eprotobuf/service_options.proto\x12\x11tecmise.protocols\x1a google/protobuf/descriptor.proto\"E\n" +
	"\vIntegration\x126\n" +
	"\x04kind\x18\x01 \x01(\x0e2\".tecmise.protocols.IntegrationKindR\x04kind*9\n" +
	"\x0fIntegrationKind\x12\n" +
	"\n" +
	"\x06LAMBDA\x10\x00\x12\b\n" +
	"\x04REST\x10\x01\x12\a\n" +
	"\x03SQS\x10\x02\x12\a\n" +
	"\x03SNS\x10\x03:c\n" +
	"\vintegration\x12\x1f.google.protobuf.ServiceOptions\x18\xb1\xea\x01 \x01(\v2\x1e.tecmise.protocols.IntegrationR\vintegrationBg\n" +
	"*com.tecmise.connector.ports.output.serviceZ9github.com/tecmise/connector-lib/pkg/ports/output/serviceb\x06proto3"

var (
	file_protobuf_service_options_proto_rawDescOnce sync.Once
	file_protobuf_service_options_proto_rawDescData []byte
)

func file_protobuf_service_options_proto_rawDescGZIP() []byte {
	file_protobuf_service_options_proto_rawDescOnce.Do(func() {
		file_protobuf_service_options_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protobuf_service_options_proto_rawDesc), len(file_protobuf_service_options_proto_rawDesc)))
	})
	return file_protobuf_service_options_proto_rawDescData
}

var file_protobuf_service_options_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protobuf_service_options_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_protobuf_service_options_proto_goTypes = []any{
	(IntegrationKind)(0),                // 0: tecmise.protocols.IntegrationKind
	(*Integration)(nil),                 // 1: tecmise.protocols.Integration
	(*descriptorpb.ServiceOptions)(nil), // 2: google.protobuf.ServiceOptions
}
var file_protobuf_service_options_proto_depIdxs = []int32{
	0, // 0: tecmise.protocols.Integration.kind:type_name -> tecmise.protocols.IntegrationKind
	2, // 1: tecmise.protocols.integration:extendee -> google.protobuf.ServiceOptions
	1, // 2: tecmise.protocols.integration:type_name -> tecmise.protocols.Integration
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	2, // [2:3] is the sub-list for extension type_name
	1, // [1:2] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protobuf_service_options_proto_init() }
func file_protobuf_service_options_proto_init() {
	if File_protobuf_service_options_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protobuf_service_options_proto_rawDesc), len(file_protobuf_service_options_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_protobuf_service_options_proto_goTypes,
		DependencyIndexes: file_protobuf_service_options_proto_depIdxs,
		EnumInfos:         file_protobuf_service_options_proto_enumTypes,
		MessageInfos:      file_protobuf_service_options_proto_msgTypes,
		ExtensionInfos:    file_protobuf_service_options_proto_extTypes,
	}.Build()
	File_protobuf_service_options_proto = out.File
	file_protobuf_service_options_proto_goTypes = nil
	file_protobuf_service_options_proto_depIdxs = nil
}
