// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.21.12
// source: protobuf/rest_response.proto

package rest

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NoContent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NoContent) Reset() {
	*x = NoContent{}
	mi := &file_protobuf_rest_response_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NoContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoContent) ProtoMessage() {}

func (x *NoContent) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_rest_response_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoContent.ProtoReflect.Descriptor instead.
func (*NoContent) Descriptor() ([]byte, []int) {
	return file_protobuf_rest_response_proto_rawDescGZIP(), []int{0}
}

var File_protobuf_rest_response_proto protoreflect.FileDescriptor

const file_protobuf_rest_response_proto_rawDesc = "" +
	"\n" +
	"\x1cprotobuf/rest_response.proto\x12\x11tecmise.responses\x1a google/protobuf/descriptor.proto\"\v\n" +
	"\tNoContentBa\n" +
	"'com.tecmise.connector.ports.output.restZ6github.com/tecmise/connector-lib/pkg/ports/output/restb\x06proto3"

var (
	file_protobuf_rest_response_proto_rawDescOnce sync.Once
	file_protobuf_rest_response_proto_rawDescData []byte
)

func file_protobuf_rest_response_proto_rawDescGZIP() []byte {
	file_protobuf_rest_response_proto_rawDescOnce.Do(func() {
		file_protobuf_rest_response_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protobuf_rest_response_proto_rawDesc), len(file_protobuf_rest_response_proto_rawDesc)))
	})
	return file_protobuf_rest_response_proto_rawDescData
}

var file_protobuf_rest_response_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_protobuf_rest_response_proto_goTypes = []any{
	(*NoContent)(nil), // 0: tecmise.responses.NoContent
}
var file_protobuf_rest_response_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protobuf_rest_response_proto_init() }
func file_protobuf_rest_response_proto_init() {
	if File_protobuf_rest_response_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protobuf_rest_response_proto_rawDesc), len(file_protobuf_rest_response_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protobuf_rest_response_proto_goTypes,
		DependencyIndexes: file_protobuf_rest_response_proto_depIdxs,
		MessageInfos:      file_protobuf_rest_response_proto_msgTypes,
	}.Build()
	File_protobuf_rest_response_proto = out.File
	file_protobuf_rest_response_proto_goTypes = nil
	file_protobuf_rest_response_proto_depIdxs = nil
}
