// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.21.12
// source: protobuf/rest_request.proto

package rest

import (
	_ "github.com/tecmise/connector-lib/pkg/ports/output/field"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FindOne struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindOne) Reset() {
	*x = FindOne{}
	mi := &file_protobuf_rest_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindOne) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindOne) ProtoMessage() {}

func (x *FindOne) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_rest_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindOne.ProtoReflect.Descriptor instead.
func (*FindOne) Descriptor() ([]byte, []int) {
	return file_protobuf_rest_request_proto_rawDescGZIP(), []int{0}
}

func (x *FindOne) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type FindAll struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Filter        string                 `protobuf:"bytes,3,opt,name=filter,proto3" json:"filter,omitempty"`
	Order         string                 `protobuf:"bytes,4,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAll) Reset() {
	*x = FindAll{}
	mi := &file_protobuf_rest_request_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAll) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAll) ProtoMessage() {}

func (x *FindAll) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_rest_request_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAll.ProtoReflect.Descriptor instead.
func (*FindAll) Descriptor() ([]byte, []int) {
	return file_protobuf_rest_request_proto_rawDescGZIP(), []int{1}
}

func (x *FindAll) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *FindAll) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *FindAll) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

func (x *FindAll) GetOrder() string {
	if x != nil {
		return x.Order
	}
	return ""
}

var File_protobuf_rest_request_proto protoreflect.FileDescriptor

const file_protobuf_rest_request_proto_rawDesc = "" +
	"\n" +
	"\x1bprotobuf/rest_request.proto\x12\x10tecmise.requests\x1a google/protobuf/descriptor.proto\x1a\x1cprotobuf/field_options.proto\">\n" +
	"\aFindOne\x123\n" +
	"\x02id\x18\x01 \x01(\x03B#\x9a\xb5\x18\brequired\xa2\xb5\x18\rID do cliente\xaa\xb5\x18\x02idR\x02id\"\x96\x02\n" +
	"\aFindAll\x12@\n" +
	"\x04page\x18\x01 \x01(\x05B,\x9a\xb5\x18\x05min=1\xa2\xb5\x18\x1fNúmero da página (padrão: 1)R\x04page\x12L\n" +
	"\x05limit\x18\x02 \x01(\x05B6\x9a\xb5\x18\x05min=1\xa2\xb5\x18)Limite de itens por página (padrão: 10)R\x05limit\x12+\n" +
	"\x06filter\x18\x03 \x01(\tB\x13\xa2\xb5\x18\x0fFiltro de buscaR\x06filter\x12N\n" +
	"\x05order\x18\x04 \x01(\tB8\x9a\xb5\x18\x0eoneof=ASC DESC\xa2\xb5\x18\"Ordem dos resultados (ASC ou DESC)R\x05orderBa\n" +
	"'com.tecmise.connector.ports.output.restZ6github.com/tecmise/connector-lib/pkg/ports/output/restb\x06proto3"

var (
	file_protobuf_rest_request_proto_rawDescOnce sync.Once
	file_protobuf_rest_request_proto_rawDescData []byte
)

func file_protobuf_rest_request_proto_rawDescGZIP() []byte {
	file_protobuf_rest_request_proto_rawDescOnce.Do(func() {
		file_protobuf_rest_request_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protobuf_rest_request_proto_rawDesc), len(file_protobuf_rest_request_proto_rawDesc)))
	})
	return file_protobuf_rest_request_proto_rawDescData
}

var file_protobuf_rest_request_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protobuf_rest_request_proto_goTypes = []any{
	(*FindOne)(nil), // 0: tecmise.requests.FindOne
	(*FindAll)(nil), // 1: tecmise.requests.FindAll
}
var file_protobuf_rest_request_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protobuf_rest_request_proto_init() }
func file_protobuf_rest_request_proto_init() {
	if File_protobuf_rest_request_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protobuf_rest_request_proto_rawDesc), len(file_protobuf_rest_request_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protobuf_rest_request_proto_goTypes,
		DependencyIndexes: file_protobuf_rest_request_proto_depIdxs,
		MessageInfos:      file_protobuf_rest_request_proto_msgTypes,
	}.Build()
	File_protobuf_rest_request_proto = out.File
	file_protobuf_rest_request_proto_goTypes = nil
	file_protobuf_rest_request_proto_depIdxs = nil
}
