// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.21.12
// source: protobuf/method_options.proto

package method

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ContextParameterKind int32

const (
	ContextParameterKind_HEADER ContextParameterKind = 0
)

// Enum value maps for ContextParameterKind.
var (
	ContextParameterKind_name = map[int32]string{
		0: "HEADER",
	}
	ContextParameterKind_value = map[string]int32{
		"HEADER": 0,
	}
)

func (x ContextParameterKind) Enum() *ContextParameterKind {
	p := new(ContextParameterKind)
	*p = x
	return p
}

func (x ContextParameterKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ContextParameterKind) Descriptor() protoreflect.EnumDescriptor {
	return file_protobuf_method_options_proto_enumTypes[0].Descriptor()
}

func (ContextParameterKind) Type() protoreflect.EnumType {
	return &file_protobuf_method_options_proto_enumTypes[0]
}

func (x ContextParameterKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ContextParameterKind.Descriptor instead.
func (ContextParameterKind) EnumDescriptor() ([]byte, []int) {
	return file_protobuf_method_options_proto_rawDescGZIP(), []int{0}
}

type HttpMethod int32

const (
	HttpMethod_GET    HttpMethod = 0
	HttpMethod_POST   HttpMethod = 1
	HttpMethod_PUT    HttpMethod = 2
	HttpMethod_DELETE HttpMethod = 3
	HttpMethod_PATCH  HttpMethod = 4
)

// Enum value maps for HttpMethod.
var (
	HttpMethod_name = map[int32]string{
		0: "GET",
		1: "POST",
		2: "PUT",
		3: "DELETE",
		4: "PATCH",
	}
	HttpMethod_value = map[string]int32{
		"GET":    0,
		"POST":   1,
		"PUT":    2,
		"DELETE": 3,
		"PATCH":  4,
	}
)

func (x HttpMethod) Enum() *HttpMethod {
	p := new(HttpMethod)
	*p = x
	return p
}

func (x HttpMethod) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HttpMethod) Descriptor() protoreflect.EnumDescriptor {
	return file_protobuf_method_options_proto_enumTypes[1].Descriptor()
}

func (HttpMethod) Type() protoreflect.EnumType {
	return &file_protobuf_method_options_proto_enumTypes[1]
}

func (x HttpMethod) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HttpMethod.Descriptor instead.
func (HttpMethod) EnumDescriptor() ([]byte, []int) {
	return file_protobuf_method_options_proto_rawDescGZIP(), []int{1}
}

type SnsIntegration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Attributes    map[string]string      `protobuf:"bytes,2,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnsIntegration) Reset() {
	*x = SnsIntegration{}
	mi := &file_protobuf_method_options_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnsIntegration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnsIntegration) ProtoMessage() {}

func (x *SnsIntegration) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_method_options_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnsIntegration.ProtoReflect.Descriptor instead.
func (*SnsIntegration) Descriptor() ([]byte, []int) {
	return file_protobuf_method_options_proto_rawDescGZIP(), []int{0}
}

func (x *SnsIntegration) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *SnsIntegration) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

type SqsIntegration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Queue         string                 `protobuf:"bytes,1,opt,name=queue,proto3" json:"queue,omitempty"`
	Fifo          bool                   `protobuf:"varint,2,opt,name=fifo,proto3" json:"fifo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SqsIntegration) Reset() {
	*x = SqsIntegration{}
	mi := &file_protobuf_method_options_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SqsIntegration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SqsIntegration) ProtoMessage() {}

func (x *SqsIntegration) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_method_options_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SqsIntegration.ProtoReflect.Descriptor instead.
func (*SqsIntegration) Descriptor() ([]byte, []int) {
	return file_protobuf_method_options_proto_rawDescGZIP(), []int{1}
}

func (x *SqsIntegration) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

func (x *SqsIntegration) GetFifo() bool {
	if x != nil {
		return x.Fifo
	}
	return false
}

type LambdaIntegration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FunctionName  string                 `protobuf:"bytes,1,opt,name=function_name,json=functionName,proto3" json:"function_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LambdaIntegration) Reset() {
	*x = LambdaIntegration{}
	mi := &file_protobuf_method_options_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LambdaIntegration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LambdaIntegration) ProtoMessage() {}

func (x *LambdaIntegration) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_method_options_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LambdaIntegration.ProtoReflect.Descriptor instead.
func (*LambdaIntegration) Descriptor() ([]byte, []int) {
	return file_protobuf_method_options_proto_rawDescGZIP(), []int{2}
}

func (x *LambdaIntegration) GetFunctionName() string {
	if x != nil {
		return x.FunctionName
	}
	return ""
}

type HttpIntegration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        HttpMethod             `protobuf:"varint,1,opt,name=method,proto3,enum=tecmise.methods.HttpMethod" json:"method,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HttpIntegration) Reset() {
	*x = HttpIntegration{}
	mi := &file_protobuf_method_options_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HttpIntegration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpIntegration) ProtoMessage() {}

func (x *HttpIntegration) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_method_options_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpIntegration.ProtoReflect.Descriptor instead.
func (*HttpIntegration) Descriptor() ([]byte, []int) {
	return file_protobuf_method_options_proto_rawDescGZIP(), []int{3}
}

func (x *HttpIntegration) GetMethod() HttpMethod {
	if x != nil {
		return x.Method
	}
	return HttpMethod_GET
}

func (x *HttpIntegration) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

var file_protobuf_method_options_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*HttpIntegration)(nil),
		Field:         40001,
		Name:          "tecmise.methods.http",
		Tag:           "bytes,40001,opt,name=http",
		Filename:      "protobuf/method_options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*SqsIntegration)(nil),
		Field:         40002,
		Name:          "tecmise.methods.sqs",
		Tag:           "bytes,40002,opt,name=sqs",
		Filename:      "protobuf/method_options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*LambdaIntegration)(nil),
		Field:         40003,
		Name:          "tecmise.methods.lambda",
		Tag:           "bytes,40003,opt,name=lambda",
		Filename:      "protobuf/method_options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*SnsIntegration)(nil),
		Field:         40004,
		Name:          "tecmise.methods.sns",
		Tag:           "bytes,40004,opt,name=sns",
		Filename:      "protobuf/method_options.proto",
	},
}

// Extension fields to descriptorpb.MethodOptions.
var (
	// optional tecmise.methods.HttpIntegration http = 40001;
	E_Http = &file_protobuf_method_options_proto_extTypes[0]
	// optional tecmise.methods.SqsIntegration sqs = 40002;
	E_Sqs = &file_protobuf_method_options_proto_extTypes[1]
	// optional tecmise.methods.LambdaIntegration lambda = 40003;
	E_Lambda = &file_protobuf_method_options_proto_extTypes[2]
	// optional tecmise.methods.SnsIntegration sns = 40004;
	E_Sns = &file_protobuf_method_options_proto_extTypes[3]
)

var File_protobuf_method_options_proto protoreflect.FileDescriptor

const file_protobuf_method_options_proto_rawDesc = "" +
	"\n" +
	"\x1dprotobuf/method_options.proto\x12\x0ftecmise.methods\x1a google/protobuf/descriptor.proto\"\xb6\x01\n" +
	"\x0eSnsIntegration\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12O\n" +
	"\n" +
	"attributes\x18\x02 \x03(\v2/.tecmise.methods.SnsIntegration.AttributesEntryR\n" +
	"attributes\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\":\n" +
	"\x0eSqsIntegration\x12\x14\n" +
	"\x05queue\x18\x01 \x01(\tR\x05queue\x12\x12\n" +
	"\x04fifo\x18\x02 \x01(\bR\x04fifo\"8\n" +
	"\x11LambdaIntegration\x12#\n" +
	"\rfunction_name\x18\x01 \x01(\tR\ffunctionName\"Z\n" +
	"\x0fHttpIntegration\x123\n" +
	"\x06method\x18\x01 \x01(\x0e2\x1b.tecmise.methods.HttpMethodR\x06method\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path*\"\n" +
	"\x14ContextParameterKind\x12\n" +
	"\n" +
	"\x06HEADER\x10\x00*?\n" +
	"\n" +
	"HttpMethod\x12\a\n" +
	"\x03GET\x10\x00\x12\b\n" +
	"\x04POST\x10\x01\x12\a\n" +
	"\x03PUT\x10\x02\x12\n" +
	"\n" +
	"\x06DELETE\x10\x03\x12\t\n" +
	"\x05PATCH\x10\x04:Y\n" +
	"\x04http\x12\x1e.google.protobuf.MethodOptions\x18\xc1\xb8\x02 \x01(\v2 .tecmise.methods.HttpIntegrationR\x04http\x88\x01\x01:V\n" +
	"\x03sqs\x12\x1e.google.protobuf.MethodOptions\x18¸\x02 \x01(\v2\x1f.tecmise.methods.SqsIntegrationR\x03sqs\x88\x01\x01:_\n" +
	"\x06lambda\x12\x1e.google.protobuf.MethodOptions\x18ø\x02 \x01(\v2\".tecmise.methods.LambdaIntegrationR\x06lambda\x88\x01\x01:V\n" +
	"\x03sns\x12\x1e.google.protobuf.MethodOptions\x18ĸ\x02 \x01(\v2\x1f.tecmise.methods.SnsIntegrationR\x03sns\x88\x01\x01Be\n" +
	")com.tecmise.connector.ports.output.methodZ8github.com/tecmise/connector-lib/pkg/ports/output/methodb\x06proto3"

var (
	file_protobuf_method_options_proto_rawDescOnce sync.Once
	file_protobuf_method_options_proto_rawDescData []byte
)

func file_protobuf_method_options_proto_rawDescGZIP() []byte {
	file_protobuf_method_options_proto_rawDescOnce.Do(func() {
		file_protobuf_method_options_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protobuf_method_options_proto_rawDesc), len(file_protobuf_method_options_proto_rawDesc)))
	})
	return file_protobuf_method_options_proto_rawDescData
}

var file_protobuf_method_options_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_protobuf_method_options_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_protobuf_method_options_proto_goTypes = []any{
	(ContextParameterKind)(0),          // 0: tecmise.methods.ContextParameterKind
	(HttpMethod)(0),                    // 1: tecmise.methods.HttpMethod
	(*SnsIntegration)(nil),             // 2: tecmise.methods.SnsIntegration
	(*SqsIntegration)(nil),             // 3: tecmise.methods.SqsIntegration
	(*LambdaIntegration)(nil),          // 4: tecmise.methods.LambdaIntegration
	(*HttpIntegration)(nil),            // 5: tecmise.methods.HttpIntegration
	nil,                                // 6: tecmise.methods.SnsIntegration.AttributesEntry
	(*descriptorpb.MethodOptions)(nil), // 7: google.protobuf.MethodOptions
}
var file_protobuf_method_options_proto_depIdxs = []int32{
	6,  // 0: tecmise.methods.SnsIntegration.attributes:type_name -> tecmise.methods.SnsIntegration.AttributesEntry
	1,  // 1: tecmise.methods.HttpIntegration.method:type_name -> tecmise.methods.HttpMethod
	7,  // 2: tecmise.methods.http:extendee -> google.protobuf.MethodOptions
	7,  // 3: tecmise.methods.sqs:extendee -> google.protobuf.MethodOptions
	7,  // 4: tecmise.methods.lambda:extendee -> google.protobuf.MethodOptions
	7,  // 5: tecmise.methods.sns:extendee -> google.protobuf.MethodOptions
	5,  // 6: tecmise.methods.http:type_name -> tecmise.methods.HttpIntegration
	3,  // 7: tecmise.methods.sqs:type_name -> tecmise.methods.SqsIntegration
	4,  // 8: tecmise.methods.lambda:type_name -> tecmise.methods.LambdaIntegration
	2,  // 9: tecmise.methods.sns:type_name -> tecmise.methods.SnsIntegration
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	6,  // [6:10] is the sub-list for extension type_name
	2,  // [2:6] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_protobuf_method_options_proto_init() }
func file_protobuf_method_options_proto_init() {
	if File_protobuf_method_options_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protobuf_method_options_proto_rawDesc), len(file_protobuf_method_options_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   5,
			NumExtensions: 4,
			NumServices:   0,
		},
		GoTypes:           file_protobuf_method_options_proto_goTypes,
		DependencyIndexes: file_protobuf_method_options_proto_depIdxs,
		EnumInfos:         file_protobuf_method_options_proto_enumTypes,
		MessageInfos:      file_protobuf_method_options_proto_msgTypes,
		ExtensionInfos:    file_protobuf_method_options_proto_extTypes,
	}.Build()
	File_protobuf_method_options_proto = out.File
	file_protobuf_method_options_proto_goTypes = nil
	file_protobuf_method_options_proto_depIdxs = nil
}
